CREATE DATABASE IF NOT EXISTS elearning_db;
USE elearning_db;

CREATE TABLE IF NOT EXISTS roles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE
);

INSERT IGNORE INTO roles (name) VALUES ('STUDENT'), ('INSTRUCTOR'), ('ADMIN');
